//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrdiniCatCe.Gui.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marche
    {
        public Marche()
        {
            this.RichiesteOrdine = new HashSet<RichiesteOrdine>();
            this.PezziInOrdine = new HashSet<PezziInOrdine>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
    
        public virtual ICollection<RichiesteOrdine> RichiesteOrdine { get; set; }
        public virtual ICollection<PezziInOrdine> PezziInOrdine { get; set; }
    }
}
