//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrdiniCatCe.Gui.Model
{
    using System;
    
    public enum ModalitaAvviso : int
    {
        Telefono = 0,
        EMail = 1,
        Segreteria = 2,
        Undefined = 3
    }
}
