//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;
using System.Windows.Documents;


namespace OrdiniCatCe.Gui.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OrdiniEntities : DbContext
    {
        public OrdiniEntities()
            : base("name=OrdiniEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public List<RichiesteOrdine> GetOrdiniByFornitore(Fornitori fornitore)
        {
            IQueryable<RichiesteOrdine> richiesteToFornitore = this.RichiesteOrdine.Where(ro => (ro.IdFornitore == fornitore.Id) && (!ro.Ordinato));
            return richiesteToFornitore.ToList();
        }

        public IQueryable<IGrouping<int?, RichiesteOrdine>> GetProdottiDaOrdinare()
        {
            return this.RichiesteOrdine.Where(ro => (!ro.Ordinato)).GroupBy(ro => ro.IdFornitore);
        }

        public Fornitori GetFornitore(int idFornitore)
        {
            return Fornitori.First(f => f.Id == idFornitore);
        }

        public Marche GetMarca(int idMarca)
        {
            return Marche.First(f => f.Id == idMarca);
        }

        public Marche GetMarca(string name)
        {
            return Marche.First(f => f.Nome == name);
        }

        public void RemoveFornitore(int id)
        {
            Fornitori f = GetFornitore(id);
            if (f == null)
            {
                return;
            }
            this.Fornitori.Remove(f);
            SaveChanges();
        }

        public void RemoveMarca(int id)
        {
            Marche m = GetMarca(id);
            if (m == null)
            {
                return;
            }
            this.Marche.Remove(m);
            this.SaveChanges();
        }
    
        public DbSet<Marche> Marche { get; set; }
        public DbSet<RichiesteOrdine> RichiesteOrdine { get; set; }
        public DbSet<Fornitori> Fornitori { get; set; }
    }
}
