//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrdiniCatCe.Gui.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PezziInOrdine
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Arrivato { get; set; }
        public Nullable<bool> Mancante { get; set; }
        public int IdRichiestaOrdine { get; set; }
        public string Codice { get; set; }
        public Nullable<decimal> PrezzoAcquisto { get; set; }
        public Nullable<decimal> PrezzoVendita { get; set; }
        public Nullable<bool> Ordinato { get; set; }
        public Nullable<bool> Ritirato { get; set; }
        public Nullable<int> IdMarca { get; set; }
        public Nullable<int> IdFornitore { get; set; }
    
        public virtual Fornitori Fornitori { get; set; }
        public virtual Marche Marche { get; set; }
        public virtual RichiesteOrdine RichiesteOrdine { get; set; }
    }
}
